#!/bin/sh
# Written by Jan Jensen based on molget (https://github.com/jensengroup/molget).
#
#? smiles2coord 0.0
#?
#? smiles2coord: bash script to get coordinates from SMILES and Cactus.
#?
#? Usage: smiles2coord chemical_name [chemical_name...]
#?
#?   -h  show this message
#?   -v  show version
#?
#? Examples:
#?
#?   ./smiles2coord "CC"
#?   (remember to "chmod 755 smiles2coord")

while getopts ":hv" opt "$@"
  do
    case $opt in
      h)  # Help message.
        grep "^#?" "$0" | cut -c 4-
        exit 0
        ;;
      v)  # Version message.
        grep "^#? molget" "$0" | cut -c 4-
        exit 0
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
  done

# Recover $@ for posterior use.
shift $((OPTIND-1))

for molecule in "$@"
  do
    echo -n $molecule

    url="https://cactus.nci.nih.gov/chemical/structure/$molecule/sdf"
    # #, [, and ] must be url-escaped
    url=$(echo "$url" | sed 's/#/%23/g')
    url=$(echo "$url" | sed 's/\[/%5B/g')
    url=$(echo "$url" | sed 's/\]/%5D/g')

    # It is also wise to translate spaces in filenames to underscores.
    # left over from molget
    molecule_wo_spaces=$(echo "$molecule" | sed 's/ /_/g')

    curl "$url" -o "$molecule_wo_spaces.sdf" 2> /dev/null

    # Check for 404 error
    if grep -q 404 "$molecule_wo_spaces.sdf"; then
        echo " FAILED"
        rm $molecule_wo_spaces.smi
        continue
    fi

    obabel -isdf "$molecule_wo_spaces.sdf" -oxyz -O "$molecule_wo_spaces.xyz" -c 2> /dev/null
    echo " SUCCESS"
  done
